services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=yopa-test-password
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mcp-n8n-network
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - mcp-n8n-network
    restart: always

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_API_KEY=yopa-test-api-key
      - N8N_ENCRYPTION_KEY=yopa-test-encryption-key
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=yopa-test-password
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - postgres
      - redis
    networks:
      - mcp-n8n-network
    restart: always

  n8n-worker:
    image: n8nio/n8n:latest
    command: worker
    environment:
      - N8N_ENCRYPTION_KEY=yopa-test-encryption-key
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=yopa-test-password
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - postgres
      - redis
      - n8n
    networks:
      - mcp-n8n-network
    restart: always

  mcp-server:
    build:
      context: ./mcp-server
    ports:
      - "1991:1991"
      - "1992:1992"
    environment:
      - MCP_SERVER_PORT=1991
      - MCP_SERVER_LOG_LEVEL=debug
      - N8N_BASE_URL=http://n8n:5678/api/v1
      - N8N_API_KEY=yopa-test-api-key
      - NODE_ENV=production
      - MCP_TRANSPORT_TYPE=sse
      - MCP_SSE_ENABLED=true
    depends_on:
      - n8n
    networks:
      - mcp-n8n-network
    restart: always

networks:
  mcp-n8n-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
