services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=yopa-test-password
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - n8n-network
    restart: always

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - n8n-network
    restart: always

  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_API_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmY2MwOTI5Zi1kNjQ2LTRkMTMtODgzZi1lNjY3NTk3MDA3NWYiLCJpc3MiOiJuOG4iLCJhdWQiOiJwdWJsaWMtYXBpIiwiaWF0IjoxNzQyMTc1Njk2fQ.E39KyK7AyKJkl9eNlSHxHVSQ-K5UiFyw9RH_DI1KDbU
      - N8N_ENCRYPTION_KEY=yopa-test-encryption-key
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=yopa-test-password
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - postgres
      - redis
    networks:
      - n8n-network
    restart: always

  n8n-worker:
    image: n8nio/n8n:latest
    command: worker
    environment:
      - N8N_ENCRYPTION_KEY=yopa-test-encryption-key
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=yopa-test-password
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0
    depends_on:
      - postgres
      - redis
      - n8n
    networks:
      - n8n-network
    restart: always

networks:
  n8n-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
