apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret
  namespace: n8n
type: Opaque
data:
  # Replace these values with your base64 encoded values
  # Example: echo -n "your-value" | base64
  N8N_ENCRYPTION_KEY: bjhuLWVuY3J5cHRpb24ta2V5LTEyMw== # base64 encoded 'n8n-encryption-key-123'
  WEBHOOK_URL: aHR0cDovL2xvY2FsaG9zdDo1Njc4 # base64 encoded 'http://localhost:5678'
  DB_POSTGRESDB_USER: bjhuCg== # base64 encoded 'n8n'
  DB_POSTGRESDB_PASSWORD: bjhuLXBhc3N3b3JkLTEyMw== # base64 encoded 'n8n-password-123'
  DB_POSTGRESDB_DATABASE: bjhu # base64 encoded 'n8n'
