apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: n8n
type: Opaque
data:
  # Replace these values with your base64 encoded values
  # Example: echo -n "your-value" | base64
  POSTGRES_USER: bjhuCg== # base64 encoded 'n8n'
  POSTGRES_PASSWORD: bjhuLXBhc3N3b3JkLTEyMw== # base64 encoded 'n8n-password-123'
  POSTGRES_DB: bjhu # base64 encoded 'n8n'
