{{- if .Values.n8n.encryptionKeySecret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "n8n-tenant-stack.n8nEncryptionKey.secretName" . }}
  labels:
    {{- include "n8n-tenant-stack.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.n8n.encryptionKeySecret.keyName }}: {{ .Values.n8n.encryptionKeySecret.value | b64enc }}
---
{{- end }}
{{- /* Placeholder for other common secrets if needed */}}
