apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n-tenant-stack.fullname" . }}-main
  labels:
    {{- include "n8n-tenant-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: n8n-main
spec:
  type: {{ .Values.n8n.main.service.type }}
  ports:
    - port: {{ .Values.n8n.main.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "n8n-tenant-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: n8n-main
