apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "n8n-tenant-stack.fullname" . }}-main-config
  labels:
    {{- include "n8n-tenant-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: n8n-main
data:
  N8N_HOST: {{ .Values.n8n.main.service.name | default (printf "%s-main" (include "n8n-tenant-stack.fullname" .)) | quote }}
  N8N_PORT: {{ .Values.n8n.main.service.port | quote }}
  N8N_PROTOCOL: "http" # Assuming http internally, TLS handled at Ingress or LB
  # WEBHOOK_URL: {{ .Values.n8n.config.webhookUrl | quote }} # Enable if ingress is configured
  EXECUTIONS_MODE: {{ .Values.n8n.config.executionsMode | quote }}
  TZ: "America/New_York" # Example, consider making this a value

  # Database Configuration
  DB_TYPE: {{ .Values.n8n.config.dbType | quote }}
  {{- if .Values.postgresql.enabled }}
  DB_POSTGRESDB_HOST: {{ include "n8n-tenant-stack.postgresql.fullname" . | quote }}
  DB_POSTGRESDB_PORT: {{ .Values.n8n.config.dbPort | quote }}
  DB_POSTGRESDB_DATABASE: {{ .Values.postgresql.auth.database | quote }} # Or .Values.n8n.config.dbName
  DB_POSTGRESDB_USER: {{ .Values.postgresql.auth.username | quote }} # Or .Values.n8n.config.dbUser
  DB_POSTGRESDB_SCHEMA: {{ .Values.n8n.config.dbSchema | quote }}
  DB_POSTGRESDB_SSL_ENABLED: {{ .Values.n8n.config.dbSslEnabled | quote }}
  {{- else }}
  # User must provide external DB connection details if postgresql.enabled is false
  DB_POSTGRESDB_HOST: {{ .Values.n8n.config.dbHost | quote }}
  DB_POSTGRESDB_PORT: {{ .Values.n8n.config.dbPort | quote }}
  DB_POSTGRESDB_DATABASE: {{ .Values.n8n.config.dbName | quote }}
  DB_POSTGRESDB_USER: {{ .Values.n8n.config.dbUser | quote }}
  DB_POSTGRESDB_SCHEMA: {{ .Values.n8n.config.dbSchema | quote }}
  DB_POSTGRESDB_SSL_ENABLED: {{ .Values.n8n.config.dbSslEnabled | quote }}
  {{- end }}

  # Queue Configuration (if executionsMode is 'queue')
  {{- if eq .Values.n8n.config.executionsMode "queue" }}
    {{- if .Values.redis.enabled }}
  QUEUE_REDIS_HOST: {{ include "n8n-tenant-stack.redis.fullname" . | quote }}
  QUEUE_REDIS_PORT: {{ .Values.n8n.config.queueRedisPort | quote }}
  QUEUE_REDIS_DB: {{ .Values.n8n.config.queueRedisDb | quote }}
    {{- else }}
  # User must provide external Redis connection details if redis.enabled is false and mode is queue
  QUEUE_REDIS_HOST: {{ .Values.n8n.config.queueRedisHost | quote }}
  QUEUE_REDIS_PORT: {{ .Values.n8n.config.queueRedisPort | quote }}
  QUEUE_REDIS_DB: {{ .Values.n8n.config.queueRedisDb | quote }}
    {{- end }}
  {{- end }}

  # Add other n8n specific environment variables here as needed
  # Example:
  # GENERIC_TIMEZONE: {{ .Values.n8n.config.genericTimezone | default "America/New_York" | quote }}
  # N8N_EMAIL_MODE: {{ .Values.n8n.config.emailMode | default "smtp" | quote }}
  # N8N_EMAIL_SMTP_HOST: {{ .Values.n8n.config.emailSmtpHost | quote }}
  # ... etc.
