{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n-tenant-stack.postgresql.fullname" . }}
  labels:
    {{- include "n8n-tenant-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: tcp-postgresql
      protocol: TCP
      name: tcp-postgresql
  selector:
    {{- include "n8n-tenant-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgresql
{{- end }}
