{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "n8n-tenant-stack.redis.fullname" . }}
  labels:
    {{- include "n8n-tenant-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: tcp-redis
      protocol: TCP
      name: tcp-redis
  selector:
    {{- include "n8n-tenant-stack.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
{{- end }}
